config/routes.rb
Rails.application.routes.draw do

  root "static_pages#index"
  get "contact", to: "static_pages#contact"
  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :users, expect: :destroy
  resources :suggest_questions
  resources :exams
  namespace :admin do
    root "home#index", as: "root"
    resources :categories
    resources :questions
    resources :answers
    resources :users
  end
end

app/models/suggest_question.rb
class SuggestQuestion < ApplicationRecord
  has_many :suggest_answers, dependent: :destroy, inverse_of: :suggest_question

  belongs_to :user
  belongs_to :category

  validates :user, presence: true
  validates :category, presence: true
  validates :content, presence: true, length: {minimum: 5}

  accepts_nested_attributes_for :suggest_answers, allow_destroy: true

  scope :recent, ->{order created_at: :desc}
end

app/controllers/suggest_questions_controller.rb
class SuggestQuestionsController < ApplicationController
  before_action :logged_in_user
  before_action :load_suggest, except: [:new, :create, :index]
  before_action :load_category, only: [:new, :create, :edit]

  def index
    @suggests = SuggestQuestion.recent.paginate page: params[:page],
      per_page: Settings.per_page
  end

  def new
    @suggest = SuggestQuestion.new
    @suggest.suggest_answers.build
  end

  def create
    @suggest = SuggestQuestion.new suggest_params
    if @suggest.save
      flash[:success] = t "suggest_user.create_success"
      redirect_to suggest_questions_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @suggest.update_attributes suggest_params
      flash[:success] = t "suggest_user.update_success"
      redirect_to suggest_questions_path
    else
      render :edit
    end
  end

  def destroy
    if @suggest.destroy
      respond_to do |format|
        format.html {redirect_to suggest_questions_url}
        format.js
      end
    else
      flash[:danger] = t "suggest_user.destroy_danger"
      redirect_to suggest_questions_path
    end
  end

  private
    def suggest_params
      params.require(:suggest_question).permit(:content, :pattern,
        :category_id,
        suggest_answers_attributes: [:id, :content, :is_correct,
        :suggest_question_id, :_destroy]).merge! user: current_user
    end

    def load_suggest
      @suggest = SuggestQuestion.find_by id: params[:id]
      if @suggest.nil?
        flash[:success] = t "suggest_user.not_found"
        redirect_to root_path
      end
    end

    def load_category
      @category = Category.all
    end

end

app/views/suggest_questions/_form.html.erb
<%= form_for @suggest do |f| %>
  <div class="form-group row">
    <%= f.label t("suggest_user.question_content"),
      class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.text_field :content, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label t("suggest_user.select_category"),
      class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.select :category_id, options_for_select(@category.collect{
        |category| [category.name, category.id]}),
        class: "btn btn-default filter-categories" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label t("suggest_user.select_type"),
      class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.radio_button :pattern,  Settings.multiple,
        checked: true, onclick: "morethan(this)" %>
      <%= t("suggest_user.multiple") %>
      <%= f.radio_button :pattern,  Settings.single,
        onclick: "lessthan(this)" %>
      <%= t("suggest_user.single") %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.fields_for :suggest_answers do |answer_builder| %>
      <%= render "suggest_answer_fields", f: answer_builder %>
    <% end %>
  </div>
  <div class="form-group row">
    <div class="col-sm-10">
      <%= link_to_add_fields t("suggest_user.add_answer"),
        f, :suggest_answers %>
    </div>
  </div>
  <div class="form-group row">
    <div class="offset-sm-2 col-sm-10">
      <%= f.submit t("suggest_user.save"),
        class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/suggest_questions/_suggest_answer_fields.html.erb
<div id="answer" class="form-group choice_question">
  <div class="col-sm-10">
    <%= f.label t("suggest_user.content_answer") %>
    <%= f.text_field :content, class: "form-control" %>
  </div>
  <div class="col-md-2 space-top-remove">
    <%= f.label t("suggest_user.is_correct") %>
    <%= f.check_box :is_correct, class: "correct" %>
  </div>
  <div class= "remove_fields">
    <%= link_to_remove_fields t("suggest_user.remove_answer"), f %>
  </div>
</div>

app/views/suggest_questions/destroy.js.erb
<% if  @suggest.destroyed? %>
  $('#suggest_<%= @suggest.id %>').fadeOut();
<% end %>

app/views/suggest_questions/edit.html.erb
<div class="container">
  <div class="col-sm-12">
    <legend><%= t "suggest_user.create_suggest" %></legend>
  </div>
  <%= render "form" %>
</div>

app/views/suggest_questions/index.html.erb
<table class="table table-striped table-bordered table-custom" cellspacing="0">
  <%= link_to t("suggest_user.create_suggest"), new_suggest_question_path,
    class: "btn btn-info btn-lg" %>
  <thead>
    <tr>
      <th><%= t "suggest_user.question_content" %></th>
      <th class = "last-column"><%= t "suggest_user.question_action" %></th>
    </tr>
  </thead>
  <tbody>
    <% @suggests.each do |suggest| %>
      <tr id="suggest_<%= suggest.id%>">
        <td><%= suggest.content %></td>
        <td class = "last-column">
          <span class="pull">
            <%= link_to edit_suggest_question_path(suggest),
              class: "btn btn-sm btn-warning" do %>
              <i class="glyphicon glyphicon-edit"></i>
            <% end %>
            <%= link_to suggest_question_path(suggest),
              method: :delete, data: {confirm: t("function.confirm_delete")},
              class: "btn btn-sm btn-danger", id: "suggest-delete",
              remote: true do %>
              <i class="glyphicon glyphicon-remove"></i>
            <% end %>
          </span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @suggests %>

app/views/suggest_questions/new.html.erb
<div class="container">
  <div class="col-sm-12">
    <legend><%= t "suggest_user.create_suggest" %></legend>
  </div>
  <%= render "form" %>
</div>