config/routes.rb
Rails.application.routes.draw do

  root "static_pages#index"
  get "contact", to: "static_pages#contact"
  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :users, expect: :destroy
  resources :suggest_questions
  resources :exams
  namespace :admin do
    root "home#index", as: "root"
    resources :categories
    resources :questions
    resources :answers
    resources :users
  end
end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div>
    <p><%= t "footer.designby" %></p>
    <ul>
      <li>
        <%= link_to t("footer.twitter"), "http://freewebsitetemplates.com/go/twitter/", id: "twitter" %>
      </li>
      <li>
        <%= link_to t("footer.facebook"), "http://freewebsitetemplates.com/go/facebook/", id: "facebook" %>
      </li>
      <li>
        <%= link_to t("footer.googleplus"), "http://freewebsitetemplates.com/go/googleplus/", id: "googleplus" %>
      </li>
      <li>
        <%= link_to t("footer.pinterest"), "http://pinterest.com/fwtemplates/", id: "pinterest"%>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/_footer_admin.html.erb
<section class="footer_bottom">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <p class="copyright"><%= t "footer_admin.introduce" %></p>
        <%= link_to t("footer_admin.design_by"), "#" %>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_header.html.erb
<div id="header">
  <%= image_tag "logo.png", alt: t("alt"), class:"logo" %>
  <ul id="navigation">
    <li><%= link_to t("header.home"), root_path %></li>
    <% if logged_in? %>
      <li><%= link_to t("header.lesson"), "#" %></li>
      <li><%= link_to t("header.contributes_question"), suggest_questions_path %></li>
      <li><%= link_to t("header.activities"), "#" %></li>
      <li><%= link_to t("header.users"), users_path %></li>
      <li class="dropdown">
        <a href="#" class="dropdown" data-toggle="dropdown">
          <%= t("header.account") %><b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to t("header.profile"), current_user %></li>
          <li><%= link_to t("header.setting"), edit_user_path(current_user) %></li>
          <hr />
          <li>
            <%= link_to t("header.logout"), logout_path, method: :delete %>
          </li>
        </ul>
      </li>
    <% else %>
    <li><%= link_to t("header.contact"), contact_path %></li>
    <li><%= link_to t("header.signup"), signup_path %></li>
    <li><%= link_to t("header.login"), login_path %></li>
  <% end %>
  </ul>
</div>

app/views/layouts/_header_admin.html.erb
<header-admin id="header-admin">
  <div id="info-bar">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 top-info hidden-xs">
          <span><%= t "header_admin.phone" %></span>
          <span><%= t "header_admin.email" %></span>
        </div>
      </div>
    </div>
  </div>
  <div id="logo-bar">
    <div class="container">
      <div class="row">
        <div class="col-md-3 col-sm-3">
          <div id="logo">
            <h1><%= link_to t("menu_admin.admin"), admin_root_path %></h1>
            <p><%= t "menu_admin.introduce" %></p>
          </div>
        </div>
        <div class="col-md-9 col-sm-9">
          <div class="navbar navbar-default navbar-static-top"
            role="navigation">
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li>
                <%= link_to t("menu_admin.user"), admin_users_path,
                  class: "white" %>
              </li>
              <li>
                <%= link_to t("menu_admin.category"), admin_categories_path,
                  class: "white" %>
              </li>
              <li>
                <%= link_to t("menu_admin.lesson"), root_path,
                  class: "white" %>
              </li>
              <li>
                <%= link_to t("menu_admin.question"), admin_questions_path,
                  class: "white" %>
              </li>
              <li>
                <%= link_to t("menu_admin.question_suggest"), root_path,
                 class: "white" %>
              </li>
              <li>
                <%= link_to t("menu_admin.exam"), admin_exams_path, class: "white" %>
              </li>
              <li>
                <%= link_to t("menu_admin.report"), root_path,
                  class: "white" %>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= t "menu_admin.account.description" %>
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to t("menu_admin.account.profile"), "#" %></li>
                  <li><%= link_to t("menu_admin.account.setting"), "#" %></li>
                  <li><%= link_to t("menu_admin.account.logout"), logout_path, method: :delete %></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</header-admin>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t "admin.title" %></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": true %>
    <%= javascript_include_tag "application", "data-turbolinks-track": true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="container">
      <%= render "layouts/header_admin" %>
      <div id="content-container">
        <div class="container">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
          <%= yield %>
        </div>
      </div>
      <%= render "layouts/footer_admin" %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t "application.title" %></title>
  <%= stylesheet_link_tag "application", media: "all",
    "data-turbolinks-track": true %>
  <%= javascript_include_tag "application", "data-turbolinks-track": true %>
  <%= csrf_meta_tags %>
  <%= render "layouts/shim" %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>
  <%= render "layouts/footer" %>
</body>
</html>